### ISSUE TITLE
如何在fragment里面的View中使用

### ISSUE THREAD

**Issue by junge89221** [Zhao-Yan-Yan/MultiStatePage#17]
如题，我想在一个Fragment中的一个子View中使用MultiStatePage

提示：
2021-10-28 09:26:11.662 25407-25407/cn.caep.stic2 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: , PID: 25407
    java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5361)
        at android.view.ViewGroup.addView(ViewGroup.java:5190)
        at android.view.ViewGroup.addView(ViewGroup.java:5130)
        at androidx.fragment.app.FragmentStateManager.addViewToContainer(FragmentStateManager.java:833)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

请问支持这个功能吗？

**Comment by junge89221** [comment]
我是在onViewCreate 生命周期里使用  MultiStatePage.bindMultiState(view)

**Comment by junge89221** [comment]
不能使用xml方式，用代码的方式可以实现吗

**Comment by Zhao-Yan-Yan** [comment]
不好意思   这几天在忙    方便贴一下代码吗

**Comment by Zhao-Yan-Yan** [comment]
我自己测了一下是正常的

**Comment by bobby-walle** [comment]
我这里也有这个错误，项目使用如下布局就会出现
1. Activity布局使用FragmentContainerView
2. FragmentContainerView中添加Fragment，在此Fragment的onViewCreated中调用MultiStatePage.bindMultiState(view)

大概跟了下代码，targetViewParent.addView(multiStateContainer, targetViewIndex, targetView.layoutParams)这里会调用到
FragmentContainerView的addView方法，这里的check会抛出如上异常
@Zhao-Yan-Yan @junge89221

**Comment by bobby-walle** [comment]
@Zhao-Yan-Yan

**Comment by Zhao-Yan-Yan** [comment]
ok 我看看 @bobby-walle
